//! Xbox 手柄预设数据定义

use crate::preset::preset_data::{PresetData, PresetMappingData, PresetConfigData};

/// FPS 游戏 Xbox 预设数据
pub fn get_fps_preset_data() -> PresetData {
    PresetData {
        name: "FPS游戏预设".to_string(),
        description: Some("适用于第一人称射击游戏的 Xbox 按键映射".to_string()),
        mappings: vec![
            PresetMappingData {
                button: "RT".to_string(),      // Xbox RT 对应 PS4 R2
                action: "MouseLeft".to_string(),
                modifiers: vec![],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "LT".to_string(),      // Xbox LT 对应 PS4 L2
                action: "MouseRight".to_string(),
                modifiers: vec![],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "X".to_string(),       // Xbox X 对应 PS4 Square
                action: "Control+z".to_string(),
                modifiers: vec!["Control".to_string()],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "Y".to_string(),       // Xbox Y 对应 PS4 Triangle
                action: "Control+y".to_string(),
                modifiers: vec!["Control".to_string()],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "A".to_string(),       // Xbox A 对应 PS4 Cross
                action: "MouseX1".to_string(),
                modifiers: vec![],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "B".to_string(),       // Xbox B 对应 PS4 Circle
                action: "Shift".to_string(),
                modifiers: vec!["Shift".to_string()],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "Start".to_string(),   // Xbox Start 对应 PS4 Options
                action: "Control+s".to_string(),
                modifiers: vec!["Control".to_string()],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "LeftStickCW".to_string(),
                action: "Shift+MouseWheelUp".to_string(),
                modifiers: vec!["Shift".to_string()],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "LeftStickCCW".to_string(),
                action: "Shift+MouseWheelDown".to_string(),
                modifiers: vec!["Shift".to_string()],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "RightStickCW".to_string(),
                action: "MouseWheelUp".to_string(),
                modifiers: vec![],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "RightStickCCW".to_string(),
                action: "MouseWheelDown".to_string(),
                modifiers: vec![],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
            PresetMappingData {
                button: "DPadUp".to_string(),
                action: "VirtualKeyboard".to_string(),
                modifiers: vec![],
                check_mode: "single".to_string(),
                check_mode_param: 300,
                trigger_threshold: 0.3,
                continually_trigger: false,
                interval: 300,
                initial_interval: 300,
                min_interval: 100,
                acceleration: 0.8,
            },
        ],
        preset_config: PresetConfigData {
            deadzone: 10,
            deadzone_left: 10,
            use_stick_as_mouse: true,
            stick_as_mouse_simulation: Some("right".to_string()),
            move_speed: 25,
            stick_rotate_trigger_threshold: 15,
            sub_preset_name: None,
            sub_preset_switch_button: None,
            sub_preset_switch_mode: None,
        },
    }
}